### PR TITLE
Add CrossTheRoadElectronics example links to README.

### PR DESCRIPTION
**Pull request by dleavitt802**
Adding those links serves as a test of my ability to access the repo.

### CODE REVIEW

**Comment by dleavitt802** [comment]
Please see you can "Approve" this Pull Request, mostly as a test to see that we can do it.  No need to understand yet what's being approved.   Also, would users @winst83 and @Dark-Matter1  please identify themselves.

**Comment by winst83** [comment]
winst83 is Simon and Dark-Matter1 is Ben

**Review by spfarrington — APPROVED** [review]
No comments.

**Comment by dleavitt802** [comment]
Thanks.  Need to get Jeremy on this and Dave.

**Review by DaveWalls — APPROVED** [review]

**Pull request merged**
